### ISSUE TITLE
having problem using command -g to see graph 

### ISSUE THREAD

**Issue by ashiknur** [prasoonbatham11/cfcli#1]
>> cfs -g ashiknur
The system cannot find the path specified.

        Rating Chart for user :  ashiknur
Traceback (most recent call last):
  File "C:\Users\FAMILY\AppData\Local\Programs\Python\Python37\Scripts\cfs-script.py", line 11, in <module>
    load_entry_point('cfs==1.0.4', 'console_scripts', 'cfs')()
  File "c:\users\family\appdata\local\programs\python\python37\lib\site-packages\cf\__main__.py", line 79, in main

    user_rating(json.loads(res.text))
  File "c:\users\family\appdata\local\programs\python\python37\lib\site-packages\cf\user_rating.py", line 23, in user_rating
    plotterm(x,y)
  File "c:\users\family\appdata\local\programs\python\python37\lib\site-packages\cf\util.py", line 68, in plotterm

    gnuplot = subprocess.Popen(["/usr/bin/gnuplot"], stdin=subprocess.PIPE)
  File "c:\users\family\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\family\appdata\local\programs\python\python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by prasoonbatham11** [comment]
Hey @ashiknur, your system does not have gnuplot installed. I will add a check and ask the user to install it based on the system type.
